### ISSUE TITLE
readme里加一个官网链接吧

### ISSUE THREAD

**Issue by songhlc** [iuap-design/iuap-design.github.io#4]
readme里加一个官网链接吧，如题，neoui里都有 这里没有

**Comment by songhlc** [comment]
另外再吐槽一下官网首页，不新开issue了
http://design.yyuap.com/
首屏默认进去上面是iuap-design图标，下面是半个手机屏幕，这样的首屏给人的视觉体验真的很差。都没有想往下翻的想法，毕竟是面子工程。

```
                                                               ----------个人属于吐槽星人体质，会随机吐槽，请大家轻喷
```

**Comment by songhlc** [comment]
另外首屏的过渡背景色我也觉得蛮丑的，后面几个页面都很好，就是首屏我建议UE多花点时间再设计一下

**Comment by GuoYongfeng** [comment]
@songhlc README已更新。
