### ISSUE TITLE
下拉框组件u-combox目前支持autocomplete吗

### ISSUE THREAD

**Issue by wangshuailian** [iuap-design/iuap-design.github.io#5]
项目中遇到下拉选项非常多的情况，输入前几个字符自动筛选出相应选项，现在的版本有这样的api吗，官方文档上并未说明

**Comment by whizbz11** [comment]
下拉项自动筛选的目前没有提供，输入框的自动筛选可以参考[这里](http://design.yyuap.com/dist/pages/webIDE/index.html#/demos/ui/autocomplete)的demo

**Comment by bluemind7788** [comment]
@wangshuailian   autocomplete现在是一个单独的控件，不是u-combox的一个功能，样式上可以做到和combox一致，如果不一致，找我把

**Comment by LiuYueKai** [comment]
目前下拉已经支持autocomplete了。
@wangshuailian
